name = "TheGoofyWizards"
author = "Pablo091213"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "913ef4f17b0b030a5d18fb21e5c45c4602cb734b20300be9a9afc116d64bb326"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
