name = "TheGoofyWizards"
author = "Pablo091213"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "735bd47f6f749c2f5f3ce65ed11d9d73e69b74166ba9f84d84e0d513833aa44a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
