name = "TheGoofyWizards"
author = "Pablo091213"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddc9653f2aa6b6a457de280f1910ff488683d42dec14c09e3bc8f0bf64077ee9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
